# Generated by Django 5.0 on 2023-12-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Type', models.CharField(choices=[('Hotels', 'Hotels'), ('Motels', 'Motels'), ('Guesthouse', 'Guesthouse'), ('Resort', 'Resort'), ('Treehouse', 'Treehouse')], default='Hotels', max_length=100)),
                ('Rating', models.IntegerField()),
                ('price', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='HotelsHomestays',
        ),
    ]
