# Generated by Django 5.0 on 2024-01-02 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_accomodation_delete_hotelshomestays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='price',
            field=models.IntegerField(),
        ),
    ]
