# Generated by Django 5.0 on 2024-03-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_accomodation_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='BicycleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourname', models.CharField(max_length=100)),
                ('youremail', models.EmailField(max_length=254)),
                ('yourmessage', models.CharField(max_length=500)),
            ],
        ),
    ]
