# Generated by Django 5.0 on 2024-03-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_bicyclemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomodation',
            name='image',
            field=models.ImageField(null=True, upload_to='accomodation_images'),
        ),
    ]
