# Generated by Django 5.0 on 2024-04-03 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_orders_review_selections'),
    ]

    operations = [
        migrations.RenameField(
            model_name='selections',
            old_name='product',
            new_name='accomodation',
        ),
    ]
