# Generated by Django 5.0 on 2024-04-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_product_selections_accomodation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinations',
            old_name='expense',
            new_name='Package_expense',
        ),
        migrations.AlterField(
            model_name='accomodation',
            name='Type',
            field=models.CharField(choices=[('Hotels', 'Hotels'), ('Guesthouse', 'Guesthouse'), ('Resort', 'Resort'), ('Treehouse', 'Treehouse')], default='Hotels', max_length=100),
        ),
    ]
