# Generated by Django 5.0 on 2024-04-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_expense_destinations_package_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicyclemodel',
            name='Type',
            field=models.CharField(choices=[('Road Bike', 'Road Bike'), ('Mountain Bike', 'Mountain Bike'), ('Folding Bike', 'Folding Bike')], default='Road_bikes', max_length=100),
        ),
    ]
