# Generated by Django 5.0 on 2024-04-08 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_bicyclemodel_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bicyclemodel',
            old_name='yourmessage',
            new_name='youraddress',
        ),
    ]
