# Generated by Django 5.0 on 2024-04-09 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_rename_yourmessage_bicyclemodel_youraddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='product',
            new_name='accomodation',
        ),
    ]
