# Generated by Django 5.0 on 2024-04-10 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_bicyclemodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bicyclemodel',
            name='user',
        ),
    ]
